// <auto-generated />
using System;
using ClanManagement.BusinessLogic.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClanManagement.BusinessLogic.Data.Migrations
{
    [DbContext(typeof(ClanMgtSysDbContext))]
    [Migration("20221030114206_ClanRenamed")]
    partial class ClanRenamed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ClanManagement.BusinessLogic.Data.Models.Clan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClanLeader")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("clan_leader");

                    b.Property<string>("ClanSeat")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("clan_seat");

                    b.Property<string>("MinorTotem")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("minor_totem");

                    b.Property<string>("MottoId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("motto_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Totem")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("totem");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Clan");
                });

            modelBuilder.Entity("ClanManagement.BusinessLogic.Data.Models.ClanMotto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClanId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("clan_id");

                    b.Property<string>("Motto")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("motto");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ClanMotto");
                });

            modelBuilder.Entity("ClanManagement.BusinessLogic.Data.Models.Name", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClanId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("clan_id");

                    b.Property<string>("Names")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Name");
                });
#pragma warning restore 612, 618
        }
    }
}
